# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nitro < Formula
  desc "Nitro is a speedy Docker-based local development environment tuned for Craft CMS"
  homepage "https://getnitro.sh/"
  version "2.0.0-beta"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/craftcms/nitro/releases/download/2.0.0-beta/nitro_darwin_x86_64.tar.gz"
    sha256 "eeecde9a0c09e85089e08f4cb08854e1e07f59020b1a3be90db00a91fa2230ab"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/craftcms/nitro/releases/download/2.0.0-beta/nitro_linux_x86_64.tar.gz"
    sha256 "85cde4a34a684247e45bc5aa81324d80141f3872229a8706dfc411e0764d57a7"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/craftcms/nitro/releases/download/2.0.0-beta/nitro_linux_arm64.tar.gz"
    sha256 "085c96ce4ac579a46d94b9d942637775d0e2b8e2787d417bd321c2786794284c"
  end

  def install
    bin.install "nitro"
  end

  test do
    system "#{bin}/nitro --version"
  end
end
