# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nitro < Formula
  desc "Nitro is a speedy Docker-based local development environment tuned for Craft CMS"
  homepage "https://getnitro.sh/"
  version "2.0.0-beta.6"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/craftcms/nitro/releases/download/2.0.0-beta.6/nitro_darwin_x86_64.tar.gz"
    sha256 "cf6d85b31c727f5af3e03dedd212f8e125209e995e882b94d4f4987658381599"
  end  
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/craftcms/nitro/releases/download/2.0.0-beta.6/nitro_darwin_arm64.tar.gz"
    sha256 "2a535893cc8b234fe3a5658d06b99c036851db2ad0b8191994cffc8a541a6fd6"  
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/craftcms/nitro/releases/download/2.0.0-beta.6/nitro_linux_x86_64.tar.gz"
    sha256 "37c30791997cc149311ec7831ed8718b330f920866c99aafb62e99ef98000f4f"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/craftcms/nitro/releases/download/2.0.0-beta.6/nitro_linux_arm64.tar.gz"
    sha256 "0ffee799ccd0ebe2a6c88f547c0f8272cadd5c0c12ce4ef4946aac81b15b5d66"
  end

  def install
    bin.install "nitro"
  end

  test do
    system "#{bin}/nitro --version"
  end
end
